services:
  - type: web
    name: apna-stay-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_0mc4gFYueopz@ep-fancy-shape-a458gdc4-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: JWT_SECRET
        value: apnastay-dev-secret-change-this-in-production-immediately
      - key: CLOUDINARY_CLOUD_NAME
        value: dftcnccer
      - key: CLOUDINARY_API_KEY
        value: 431878442119442
      - key: CLOUDINARY_API_SECRET
        value: U33_BftweRzj3maqdo4BO5NP-Gc
